In [1]:
import pandas as pd
df_customers = pd.read_excel(r'D:\Coding Ninjas\Python\17 Pandas - II\customers.xlsx', sheet_name ="customers")
df_purchases = pd.read_excel(r'D:\Coding Ninjas\Python\17 Pandas - II\customers.xlsx', sheet_name ="purchases")
df_products = pd.read_excel(r'D:\Coding Ninjas\Python\17 Pandas - II\customers.xlsx', sheet_name ="products")

<h5><b><center> Statistical Operations

In [2]:

df_purchases['purch_date'] = pd.to_datetime(df_purchases['purch_date'])
df_purchases['paid'] = df_purchases['paid'].str.replace('$','').str.replace(',','').astype('float')

In [3]:
# Mean, Median, Mode, Max, Min, Sum, Count

print("Mean of Values for each column:\n", df_purchases.mean(),'\n\n')

numeric_cols = df_purchases.select_dtypes(include=['number'])
mean_values = numeric_cols.mean()
print("Mean of numeric columns only:\n",mean_values,'\n\n')

print("mean of specific column (paid):\n", df_purchases['paid'].mean())

Mean of Values for each column:
 Unnamed: 0                   2999.5
id                           3000.5
purch_date      2019-05-13 20:18:00
customer_num             500.889333
product_num               30.140667
amount                    10.576167
paid                     548.871353
dtype: object


Mean of numeric columns only:
 Unnamed: 0      2999.500000
id              3000.500000
customer_num     500.889333
product_num       30.140667
amount            10.576167
paid             548.871353
dtype: float64


mean of specific column (paid):
 548.8713533333333

In [4]:
print("Median for each column of dataset:\n",df_purchases.median(),'\n\n')

numeric_cols2 = df_purchases.select_dtypes(include= ['number'])
median_value = numeric_cols2.median()
print("Median Calculation for Non-Numeric column:\n",median_value, '\n\n')

Median for each column of dataset:
 Unnamed: 0                   2999.5
id                           3000.5
purch_date      2019-04-26 00:00:00
customer_num                  511.0
product_num                    30.0
amount                         11.0
paid                          422.7
dtype: object


Median Calculation for Non-Numeric column:
 Unnamed: 0      2999.5
id              3000.5
customer_num     511.0
product_num       30.0
amount            11.0
paid             422.7
dtype: float64

In [5]:
max_values = df_purchases.max(numeric_only=True)
print('Maximum Values:\n',max_values,'\n')                       # returns results in float data type, 
print("maximum values in integer data type:\n",max_values.astype(int))

# similary we can do it for Sum() , count()

Maximum Values:
 Unnamed: 0      5999.0
id              6000.0
customer_num    1000.0
product_num       60.0
amount            20.0
paid            1990.8
dtype: float64

maximum values in integer data type:
 Unnamed: 0      5999
id              6000
customer_num    1000
product_num       60
amount            20
paid            1990
dtype: int64

<h5><b><center> Frequency Analysis

In [6]:
company_counts = df_products['company'].value_counts()
print("Frequency distribution of company column:",company_counts)

Frequency distribution of company column: company
Livepath        2
Ntag            2
Browsezoom      2
Vitz            2
Cogibox         2
Dynazzy         1
Oloo            1
Oozz            1
Photojam        1
Skipfire        1
Meezzy          1
Meevee          1
Twitterworks    1
Photofeed       1
Dynabox         1
Aibox           1
Brainsphere     1
Eare            1
Trunyx          1
Realcube        1
Innojam         1
Zoombox         1
Skinder         1
Photolist       1
Muxo            1
Voonder         1
Skyble          1
Linkbuzz        1
Quatz           1
Realpoint       1
Mynte           1
Oodoo           1
Meemm           1
Wordware        1
Edgeclub        1
Jabbersphere    1
Thoughtstorm    1
Skiba           1
Gevee           1
Babbleopia      1
Fliptune        1
Eimbee          1
Topiclounge     1
Flipstorm       1
Digitube        1
Zazio           1
Fanoodle        1
Yakijo          1
Eazzy           1
Quinu           1
Name: count, dtype: int64

<h5><b><center> Data Aggregations

In [7]:
df_purchases.aggregate('max')

Unnamed: 0                     5999
id                             6000
purch_date      2019-12-06 00:00:00
customer_num                   1000
product_num                      60
amount                           20
paid                         1990.8
dtype: object

In [8]:
df_products['cost'].aggregate(['max','min'])

max    $99.54
min    $13.83
Name: cost, dtype: object

<h5><b><center> Sorting a DataFrame

In [9]:
sorted_purchase = df_purchases.sort_values(by = 'amount')
print("Sorted purchase by amount(ascending):\n",sorted_purchase)            # Ascending

Sorted purchase by amount(ascending):
       Unnamed: 0    id purch_date  customer_num  product_num  amount     paid
5033        5033  5034 2019-05-17           680           23       1    16.27
86            86    87 2019-01-04           651           25       1    73.70
5061        5061  5062 2019-05-18           540           52       1    98.74
3363        3363  3364 2019-03-29           457           10       1    88.99
1825        1825  1826 2019-10-04           948           19       1    22.83
...          ...   ...        ...           ...          ...     ...      ...
5037        5037  5038 2019-05-17           508           42      20  1750.20
10            10    11 2019-01-03           727           47      20   966.40
11            11    12 2019-01-03           589           30      20   459.20
5985        5985  5986 2019-06-20           238           33      20  1644.40
92            92    93 2019-01-04           312            9      20   600.20

[6000 rows x 7 columns]

In [10]:
sorted_cust = df_customers.sort_values(by = 'first_name', ascending=False)
print("sorted customers by  first name:\n",sorted_cust.head(3))

sorted customers by  first name:
       id first_name  last_name                             email  gender  \
345  346      Zelig     Hawick  zhawick9l@nationalgeographic.com    Male
737  738       Zara      Speed                 zspeedkh@ucsd.edu  Female
387  388  Zackariah  Kalkhoven       zkalkhovenar@soundcloud.com    Male

     street_num street_name street_suffix        city       state  postcode
345        94.0  Hazelcrest       Parkway      Fresno  California   93750.0
737         NaN       Green         Alley    Brooklyn    New York   11236.0
387         NaN      Hanson        Circle  Fort Worth       Texas   76162.0

In [11]:
multi_sort= df_products.sort_values(by=['company', 'cost'],ascending = [True, False])
print("sorted products by company(Asc) and cost(Desc):\n",multi_sort.head(3))

sorted products by company(Asc) and cost(Desc):
     Unnamed: 0  id                 product    cost      company
17          17  18               Squid Ink  $56.33        Aibox
49          49  50  Silicone Paper 16.5x24  $63.98   Babbleopia
18          18  19   Loaf Pan - 2 Lb, Foil  $22.83  Brainsphere

In [12]:
# idxmax (computes the index labels of the maximum value)
id_max_products = df_products.idxmax(numeric_only=True)
print("Index of maximum elements along columns:\n",id_max_products)

Index of maximum elements along columns:
 Unnamed: 0    59
id            59
dtype: int64

<h5><b><center> Group By

In [13]:
df_products['cost']= df_products['cost'].str.replace("$",'').str.replace(",",'').astype('float')

In [14]:
df_products.head()

   Unnamed: 0  id                           product   cost   company
0           0   1              Liners - Baking Cups   6.36  Skipfire
1           1   2        Nori Sea Weed - Gold Label  85.74   Dynazzy
2           2   3                Bar Bran Honey Nut  65.40      Ntag
3           3   4        Soup - Campbells Beef Stew  68.16  Photojam
4           4   5  Wine - Shiraz Wolf Blass Premium  87.39      Eare

In [15]:
group_by_company =df_products.groupby('company')
avg_cost = group_by_company['cost'].mean()                  # avg cost of products group by company
total_products = group_by_company['product'].count()       # calculate total no. of products per company

print("average cost of products per company: \n",avg_cost.head())
print("\n Total cost of products per company: \n",total_products.head() )

average cost of products per company:
 company
Aibox          56.330
Babbleopia     63.980
Brainsphere    22.830
Browsezoom     41.050
Cogibox        51.135
Name: cost, dtype: float64

 Total cost of products per company:
 company
Aibox          1
Babbleopia     1
Brainsphere    1
Browsezoom     2
Cogibox        2
Name: product, dtype: int64

In [16]:
group_by_company['cost'].aggregate(['mean','median','std','count']).sort_index(ascending=False).head()          

# also we can use aggregate with groupby and we sort it out in descending order

           mean  median  std  count
company
Zoombox   16.27   16.27  NaN      1
Zazio     20.53   20.53  NaN      1
Yakijo    73.05   73.05  NaN      1
Wordware  87.51   87.51  NaN      1
Voonder   82.22   82.22  NaN      1

In [17]:
# if we want to sort the table on the basis of another column, we can use following way 

group_by_company['cost'].aggregate(['mean','median','std','count']).sort_values("mean",ascending=False).head()  

# now the index is "company" and we can reset back yo default 0,1,2,3 .... by useing reset_index()

            mean  median       std  count
company
Skyble    99.540  99.540       NaN      1
Dynabox   99.400  99.400       NaN      1
Eimbee    98.740  98.740       NaN      1
Linkbuzz  95.680  95.680       NaN      1
Livepath  94.105  94.105  7.233702      2

In [18]:
# Group by  "purch_date" and calculate the total "paid" amount per date
total_paid_per_date = df_purchases.groupby('purch_date')['paid'].sum()
print("TOTAL PAID AMOUNT PER DATE:\n",total_paid_per_date)

TOTAL PAID AMOUNT PER DATE:
 purch_date
2019-01-03    20468.33
2019-01-04    48529.13
2019-01-05    38643.67
2019-01-06    32345.29
2019-02-03    28183.50
                ...
2019-11-06    24778.05
2019-12-03    27691.62
2019-12-04    37100.59
2019-12-05    20845.55
2019-12-06    26410.08
Name: paid, Length: 108, dtype: float64

In [19]:
# group by "product_num" and calculate the average 'amount purchased per product

avg_amt_per_product = df_purchases.groupby("product_num")['amount'].mean()
print("Average amount per product grouped by product number:\n",avg_amt_per_product.head())

Average amount per product grouped by product number:
 product_num
1     9.958763
2    10.861386
3     9.754902
4    10.126214
5    11.096774
Name: amount, dtype: float64

In [20]:
df_products.sort_values('cost').groupby("company")['cost']

<h5><b><center> Altering the index

In [21]:
# set_index() we can make any column as an index

df_customers.set_index('id',inplace = True)
print("\n DataFrame with 'id' as index:",df_customers.head())

 DataFrame with 'id' as index:    first_name   last_name                      email  gender  street_num  \
id
1      Romain   Southcott  rsouthcott0@clickbank.net    Male         1.0
2      Cosimo   Molyneaux      cmolyneaux1@wiley.com    Male         NaN
3       Bambi     Westrip     bwestrip2@symantec.com  Female      4057.0
4      Roarke  Pankettman     rpankettman3@wiley.com    Male        74.0
5     Mikaela    Althorpe           malthorpe4@51.la     NaN         NaN

   street_name street_suffix         city       state  postcode
id
1    Trailsway          Road    San Diego  California   92127.0
2          NaN           NaN      El Paso       Texas       NaN
3     Arkansas        Circle  San Antonio       Texas   78220.0
4         Debs         Point      Memphis   Tennessee   38150.0
5          2nd         Drive          NaN         NaN   83732.0

In [22]:
# also we can reset index back to original default one

df_customers.reset_index(inplace=True)
print(" Dataframe after resetting index:\n", df_customers.head(3))

 Dataframe after resetting index:
    id first_name  last_name                      email  gender  street_num  \
0   1     Romain  Southcott  rsouthcott0@clickbank.net    Male         1.0
1   2     Cosimo  Molyneaux      cmolyneaux1@wiley.com    Male         NaN
2   3      Bambi    Westrip     bwestrip2@symantec.com  Female      4057.0

  street_name street_suffix         city       state  postcode
0   Trailsway          Road    San Diego  California   92127.0
1         NaN           NaN      El Paso       Texas       NaN
2    Arkansas        Circle  San Antonio       Texas   78220.0

In [23]:
df_customers.set_index("email").head()          # we set email as index here

,id,first_name,last_name,gender,street_num,street_name,street_suffix,city,state,postcode
email,,,,,,,,,,
rsouthcott0@clickbank.net,1,Romain,Southcott,Male,1.0,Trailsway,Road,San Diego,California,92127.0
cmolyneaux1@wiley.com,2,Cosimo,Molyneaux,Male,NaN,NaN,NaN,El Paso,Texas,NaN
bwestrip2@symantec.com,3,Bambi,Westrip,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
rpankettman3@wiley.com,4,Roarke,Pankettman,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
malthorpe4@51.la,5,Mikaela,Althorpe,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

<h5><center><b> Pivot Tables

In [24]:
df_purchases.head(3)

   Unnamed: 0  id purch_date  customer_num  product_num  amount    paid
0           0   1 2019-01-03           823           27      12  568.92
1           1   2 2019-01-03           606           28      14  395.36
2           2   3 2019-01-03           955            9      17  510.17

In [25]:
pd.pivot_table(data=df_purchases, values = 'amount', index = 'purch_date', columns = 'product_num', aggfunc='sum', fill_value= 0)

product_num,1,2,3,4,5,6,7,8,9,10,...,51,52,53,54,55,56,57,58,59,60
purch_date,,,,,,,,,,,,,,,,,,,,,
2019-01-03,36,0,0,0,7,0,12,18,47,0,...,0,0,18,0,6,0,0,21,0,1
2019-01-04,46,34,3,7,16,0,0,0,38,30,...,0,5,9,5,0,27,36,0,0,0
2019-01-05,16,22,17,8,0,18,10,3,31,21,...,0,34,0,36,0,14,72,0,0,6
2019-01-06,0,39,16,20,0,0,0,11,16,0,...,0,6,55,20,0,0,17,0,17,26
2019-02-03,18,11,19,15,0,18,32,0,10,0,...,0,0,33,10,0,6,20,0,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-11-06,2,0,11,0,0,6,0,15,13,13,...,0,0,0,0,3,8,0,0,0,0
2019-12-03,0,0,19,0,0,0,16,26,3,12,...,0,23,14,15,0,13,13,0,7,0
2019-12-04,6,18,6,17,30,8,17,0,34,0,...,0,0,41,18,25,0,16,25,14,9
2019-12-05,0,0,19,16,0,20,0,6,0,0,...,4,29,19,17,0,0,9,0,25,12
2019-12-06,0,4,0,0,15,6,16,5,0,0,...,14,0,0,15,0,17,0,20,0,0

In [30]:
df_products.head(3)

   Unnamed: 0  id                     product   cost   company
0           0   1        Liners - Baking Cups   6.36  Skipfire
1           1   2  Nori Sea Weed - Gold Label  85.74   Dynazzy
2           2   3          Bar Bran Honey Nut  65.40      Ntag

In [32]:
pd.pivot_table(df_products, values = 'cost', index = 'product', aggfunc= 'mean' ).head()

                                cost
product
Apple - Delicious, Golden     36.670
Aromat Spice / Seasoning      61.340
Bagel - Everything Presliced  87.050
Bagel - Whole White Sesame    90.480
Bar Bran Honey Nut            69.225

In [34]:
# Extarcting the month from the date column and adding it to the DF

df_purchases['month'] = df_purchases['purch_date'].dt.month

In [37]:
pd.pivot_table(df_purchases, values = 'paid', index='month', columns='product_num', aggfunc='sum')

product_num,1,2,3,4,5,6,7,8,9,10,...,51,52,53,54,55,56,57,58,59,60
month,,,,,,,,,,,,,,,,,,,,,
1,612.48,7574.34,2354.40,2385.60,2009.97,1678.86,219.38,1350.08,3821.22,4114.85,...,NaN,4426.51,5806.34,2305.19,51.30,841.73,8196.43,1534.05,1262.76,1360.26
2,133.56,2057.76,1962.00,2832.00,1485.63,4266.46,525.54,2401.38,726.85,1512.83,...,819.40,2756.80,2443.98,1700.55,176.55,328.48,1103.56,NaN,733.88,920.01
3,1120.77,21455.72,12855.01,18943.63,33877.51,33985.78,2706.93,15617.01,6716.26,23533.36,...,26109.72,18950.15,25528.64,10404.03,1878.85,3739.25,13869.31,23510.28,19629.87,5464.60
4,1793.83,25340.50,14454.02,15310.04,30334.90,19931.40,3264.09,8056.74,3873.26,19042.76,...,10236.85,24267.39,18036.68,12522.26,1239.94,5186.67,10418.74,17122.26,17688.27,6812.28
5,931.57,10460.29,12698.70,10403.88,16365.56,24811.79,2528.62,5500.62,3635.46,12730.73,...,11254.29,11286.97,11064.56,5495.81,1616.70,2900.48,6631.00,6746.87,12181.86,8608.35
6,673.20,9311.38,4821.26,3443.34,4631.67,5457.10,1388.44,3822.37,1469.96,2425.82,...,6370.52,9270.78,6353.59,5232.07,1330.38,733.75,5009.99,5190.19,8401.78,5709.02
7,108.12,2486.46,2207.92,886.08,2186.50,NaN,666.72,2849.58,1344.50,3687.74,...,6378.91,3186.33,3577.88,869.17,617.30,328.48,2030.14,2545.17,1033.92,1772.46
8,111.06,840.23,130.80,5426.96,6364.73,3968.80,401.07,1350.08,1081.58,3815.88,...,4297.71,691.18,2295.86,718.01,171.00,1108.62,1235.34,4112.76,2539.66,1319.80
9,197.16,2014.07,4512.60,1499.52,2750.97,904.85,144.36,1096.94,1158.43,3201.85,...,2941.28,1150.38,3332.70,264.53,119.70,1380.71,1778.85,1680.15,1337.04,1510.26
10,76.32,1793.70,1177.20,2181.12,4003.41,4004.44,185.81,295.33,1929.05,2829.87,...,256.10,7103.36,2294.40,453.48,324.90,146.98,1495.44,5058.00,4011.12,1277.82
11,55.44,2557.58,3254.97,1090.56,4150.05,3215.78,511.71,3122.06,570.19,1790.45,...,1280.44,1974.80,2962.40,642.43,203.10,307.95,1130.99,NaN,1485.60,1937.34
12,38.16,1886.28,2689.20,2249.28,3932.55,3373.48,677.67,1533.19,1110.37,1067.88,...,1355.76,4087.87,5460.44,2456.35,145.41,615.90,2385.55,3287.25,3416.88,865.62

In [ ]:
                                                        # crosstabs

pd.crosstab(index = df_purchases['month'], columns=df_purchases['product_num'])   # gives count (frequencies)

product_num,1,2,3,4,5,6,7,8,9,10,...,51,52,53,54,55,56,57,58,59,60
month,,,,,,,,,,,,,,,,,,,,,
1,8,8,3,4,3,1,2,4,9,5,...,0,5,6,6,1,4,9,2,1,4
2,3,2,2,3,1,5,3,4,4,2,...,1,2,3,3,2,2,2,0,2,4
3,18,24,24,29,36,30,21,34,19,26,...,33,25,26,27,19,22,22,36,27,13
4,28,26,22,24,35,20,24,19,15,18,...,12,20,25,30,16,25,17,23,23,15
5,16,15,21,17,19,22,21,16,16,17,...,15,12,13,17,18,13,12,12,17,22
6,10,9,9,7,7,4,9,12,6,4,...,10,8,9,14,14,5,8,9,13,11
7,2,2,4,2,3,0,4,6,4,3,...,8,3,6,4,6,1,2,3,2,4
8,4,4,1,6,7,3,3,3,4,6,...,5,2,2,1,3,5,1,6,3,4
9,3,3,6,2,3,2,2,2,3,3,...,4,2,5,1,1,6,3,2,2,3
10,2,2,1,4,3,4,1,1,6,3,...,1,6,4,1,4,2,3,8,3,2
11,2,4,5,3,4,4,4,5,3,3,...,1,2,4,1,3,2,2,0,1,4
12,1,2,4,2,3,3,3,4,3,2,...,3,4,9,6,3,2,4,3,5,2

<h5><b><center> Questions

In [26]:
# Reset and display first 5 rows  ( original index is completely removed )
Customers = pd.read_excel('customers.xlsx')
Customers.reset_index(drop=True, inplace=True)                      # drop=True tells pandas to remove the old index entirely, not keep it as a column
print(Customers.head())

   id first_name   last_name                      email  gender  street_num  \
0   1     Romain   Southcott  rsouthcott0@clickbank.net    Male         1.0
1   2     Cosimo   Molyneaux      cmolyneaux1@wiley.com    Male         NaN
2   3      Bambi     Westrip     bwestrip2@symantec.com  Female      4057.0
3   4     Roarke  Pankettman     rpankettman3@wiley.com    Male        74.0
4   5    Mikaela    Althorpe           malthorpe4@51.la     NaN         NaN

  street_name street_suffix         city       state  postcode
0   Trailsway          Road    San Diego  California   92127.0
1         NaN           NaN      El Paso       Texas       NaN
2    Arkansas        Circle  San Antonio       Texas   78220.0
3        Debs         Point      Memphis   Tennessee   38150.0
4         2nd         Drive          NaN         NaN   83732.0

In [27]:
 #setting the index ( setting the state as index and printing number of columns in th DF)

df = pd.read_excel('customers.xlsx')
df.set_index('state',inplace =True)
print(df.shape[1])

10

In [28]:
# average car price by engine type
'''
df=pd.read_excel('car_price_dataset.xlsx')
groupby = df.groupby('enginetype')['price'].mean()
print(groupby)
'''

"\ndf=pd.read_excel('car_price_dataset.xlsx')\ngroupby = df.groupby('enginetype')['price'].mean()\nprint(groupby)\n"

In [29]:
# Gender Data Cleaning

df = pd.read_excel('customers.xlsx')
gender_mode = df['gender'].mode()[0]
df['gender'].fillna(gender_mode, inplace  =True)

print(df['gender'].notna().sum())

1000

C:\Users\sachi\AppData\Local\Temp\ipykernel_19392\1211601084.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna(gender_mode, inplace  =True)

<h5><b> Exporting Data Frame to CSV or Excel

In [40]:
df.to_csv('output.csv', index=False)

In [41]:
df_purchases.to_excel('output_purch.xlsx', index =False)

In [ ]:
# Reshape Data using melt function and sort this by Salary in Descending order and retrieve the first highest record and join :Department and Country 

data = {
    'Department': ['Data Analyst', 'Data Analyst', 'Data Analyst', 'Data Analyst'],
    'India': [50000, 55000, 60000, 65000],
    'US': [70000, 75000, 80000, 85000]
}

# Write your code here

df = pd.DataFrame(data)

melted = pd.melt(df, id_vars=['Department'], value_vars = ['India','US'],var_name ='Country', value_name = "Salary").sort_values(by= ['Salary'], ascending = False)

row =melted.iloc[0]
print(row['Department']+' in '+row['Country'])

Data Analyst in US